#!/bin/bash
#PJM --gname [project_name]
# #PJM --rsc-list "rscgrp=small"
#PJM --rsc-list "node=1"
#PJM --rsc-list "elapse=00:10:00"
#PJM --rsc-list "node-mem=23Gi"
#PJM -x PJM_LLIO_GFSCACHE=/vol0006
#PJM -N "mm"
#PJM -o  "%n.%j.out"
#PJM -e  "%n.%j.err"
#PJM -s


EXE=../run.x

export OMP_STACKSIZE=256M
export OMP_WAIT_POLICY=ACTIVE
#export XOS_MMM_L_HPAGE_TYPE=hugetlbfs #none
export XOS_MMM_L_PAGING_POLICY=demand:demand:demand
#export XOS_MMM_L_ARENA_LOCK_TYPE=1 #0

NS=20
{
OMP_NUM_THREADS=1 FLIB_CNTL_BARRIER_ERR=FALSE ${EXE} ${NS}
OMP_NUM_THREADS=4 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=8 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=12 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=24 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
OMP_NUM_THREADS=48 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
} > output.${NS}

NS=100
{
OMP_NUM_THREADS=1 FLIB_CNTL_BARRIER_ERR=FALSE ${EXE} ${NS}
OMP_NUM_THREADS=4 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=8 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=12 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=24 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
OMP_NUM_THREADS=48 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
} > output.${NS}

NS=400
{
OMP_NUM_THREADS=1 FLIB_CNTL_BARRIER_ERR=FALSE ${EXE} ${NS}
OMP_NUM_THREADS=4 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=8 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=12 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=24 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
OMP_NUM_THREADS=48 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
} > output.${NS}

NS=800
{
OMP_NUM_THREADS=1 FLIB_CNTL_BARRIER_ERR=FALSE ${EXE} ${NS}
OMP_NUM_THREADS=4 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=8 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=12 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=24 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
OMP_NUM_THREADS=48 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
} > output.${NS}

NS=1200
{
OMP_NUM_THREADS=1 FLIB_CNTL_BARRIER_ERR=FALSE ${EXE} ${NS}
OMP_NUM_THREADS=4 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=8 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=12 FLIB_BARRIER=HARD ${EXE} ${NS}
OMP_NUM_THREADS=24 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
OMP_NUM_THREADS=48 FLIB_BARRIER=SOFT OMP_PLACES=cores OMP_PROC_BIND=spread numactl --interleave=all ${EXE} ${NS}
} > output.${NS}
