FC=mpifrt
FCFLAGS=-g -O2 -Kopenmp
LINK_FLAGS=$(FCFLAGS)
LIB=

.SUFFIXES: .o .F90

SRC= main.F90
OBJ= $(SRC:.F90=.o)

EXE=run.x

$(EXE): $(OBJ)
	$(FC) $(LINK_FLAGS) -o $@ $(OBJ) $(LIB)

main.o: main.F90

.F90.o:
	$(FC) $(FCFLAGS) -c -o $@ $<

.PHONY:
clean:
	rm -f *.o *.mod *.lst

.PHONY:
veryclean: clean
	rm -f $(EXE)
