FC=frtpx
FFLAGS=-g -Cpp -V -KA64FX -KSVE -Kfast -Knoomitfp -Ksimd=auto -Kswp -Kswp_policy=auto \
       -Koptmsg=2 -Nlst=t 
##########################################################################
SRC= main.f90 mykernel.f90 mytype.f90
	

OBJS = $(SRC:.f90=.o)

.SUFFIXES: .f90 .o

run.x: $(OBJS)
	$(FC) $(FFLAGS) $(OBJS) -o $@

.f90.o:
	$(FC) $(FFLAGS) -c $< -o $@

main.o: mytype.o mykernel.o main.f90

mykernel.o: mytype.o mykernel.f90

mytype.o: mytype.f90

.PHONY: clean
clean:
	rm -f *.o *~ *.mod *.lst

.PHONY: veryclean
veryclean: clean
	rm -f *.x

